apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops1
spec:
  ingressClassName: nginx
  rules:
  - host: devsecops.nexapointit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsecops1
            port:
              number: 80
